parameters:
    bigfoot_context.language_back.loader.class: 'Bigfoot\Bundle\ContextBundle\Loader\LanguageBackLoader'
services:
    # Context Service
    bigfoot_context.service.context:
        class: Bigfoot\Bundle\ContextBundle\Service\ContextService
        arguments:
            - '@bigfoot_context.chain.loader'
            - '%bigfoot_context.contexts%'
            - '%bigfoot_context.entities%'
            - '@kernel'
            - '@request_stack'

    # Context Manager
    bigfoot_context.manager.context:
        class: Bigfoot\Bundle\ContextBundle\Manager\ContextManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%bigfoot_context.entities%'

    # Context Repository
    bigfoot_context.repository.context:
        class: Bigfoot\Bundle\ContextBundle\Entity\ContextRepository
        arguments: ['BigfootContextBundle:Context']
        factory: ["@doctrine.orm.entity_manager", getRepository]
        calls:
            - [setSession, ['@session']]
            - [setContextService, ['@bigfoot_context']]

    # Context Voter
    bigfoot_context.voter.context:
        class: Bigfoot\Bundle\ContextBundle\Security\Core\Authorization\Voter\ContextVoter
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: security.voter }

    # Context Alias
    bigfoot_context:
        alias: bigfoot_context.service.context

    # Context Type
    bigfoot_context.form.type.context:
        class: Bigfoot\Bundle\ContextBundle\Form\Type\ContextType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@session'
            - '@security.authorization_checker'
            - '@bigfoot_context'
            - '@bigfoot_context.manager.context'
        tags:
            - { name: form.type, alias: bigfoot_context }

    # Context Form Extension
    bigfoot_context.form.extension.context:
        class: Bigfoot\Bundle\ContextBundle\Form\Extension\ContextExtension
        arguments:
            - '@bigfoot_context.repository.context'
        tags:
            - { name: form.type_extension, alias: entity, extended_type: Symfony\Bridge\Doctrine\Form\Type\EntityType }

    # Context Twig Extension
    bigfoot_context.twig.extension.context:
        class: Bigfoot\Bundle\ContextBundle\Twig\Extension\ContextExtension
        arguments:
            - '@bigfoot_context'
        tags:
            - { name: twig.extension }

    # Menu Subscriber
    bigfoot_context.subscriber.menu:
        class: Bigfoot\Bundle\ContextBundle\Subscriber\MenuSubscriber
        arguments:
            - '@security.token_storage'
        tags:
            - { name: kernel.event_subscriber }

    # Form Subscriber
    bigfoot_context.subscriber.form:
        class: Bigfoot\Bundle\ContextBundle\Subscriber\FormSubscriber
        arguments:
            - '@form.factory'
            - '@bigfoot_context'
        tags:
            - { name: kernel.event_subscriber }

    # Doctrine Subscriber
    bigfoot_context.subscriber.doctrine:
        class: Bigfoot\Bundle\ContextBundle\Subscriber\DoctrineSubscriber
        arguments:
            - '@bigfoot_context'
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    # Loader Chain
    bigfoot_context.chain.loader:
        class: Bigfoot\Bundle\ContextBundle\Loader\LoaderChain

    # Abstract Loader
    bigfoot_context.loader.abstract:
        class: Bigfoot\Bundle\ContextBundle\Loader\AbstractLoader
        abstract: true
        calls:
            - [setRequestFromStack, ['@request_stack']]
            - [setContexts, ['%bigfoot_context.contexts%']]

    # BackOffice Language Loader
    bigfoot_context.language_back.loader:
        class: '%bigfoot_context.language_back.loader.class%'
        parent: bigfoot_context.loader.abstract
        tags:
            - { name: bigfoot_context.loader }
